# action.yml
name: "Install Snowflake CLI"
description: "Download and install snowflake-cli"
branding:
  icon: "terminal"
  color: "blue"

inputs:
  cli-version:
    description: "Snowflake CLI version (by default, installs the latest version)"
    required: false

  default-config-file-path:
    description: "Path to the default config file"
    required: false
    default: "./config.toml"

  custom-github-ref:
    description: "GitHub branch, tag, or commit to install from (if set, installs from GitHub; otherwise, installs from PyPI)"
    required: false

  use-oidc:
    description: "Enable OIDC authentication"
    required: false
    default: "false"

  oidc-token-name:
    description: >-
      "Name of the token environment variable for OIDC authentication."
      " By default it's set for [temporary connections](https://docs.snowflake.com/en/developer-guide/snowflake-cli/connecting/configure-connections#use-a-temporary-connection), "
      "however it can be changed to SNOWFLAKE_CONNECTIONS_<NAME>_TOKEN to work with named connections."
    required: false
    default: "SNOWFLAKE_TOKEN"

runs:
  using: "composite"
  steps:
    - name: add extra telemetry data
      shell: bash
      run: echo "SF_GITHUB_ACTION=true" >> "$GITHUB_ENV"

    - uses: astral-sh/setup-uv@v6
      with:
        python-version: "3.12"

    - name: Either cli-version or custom-github-ref allowed
      if: ${{ inputs.cli-version != '' && inputs.custom-github-ref != '' }}
      shell: bash
      run: |
        echo "You cannot set BOTH cli-version and custom-github-ref"
        exit 1

    - name: Install snowflake-cli (specific version)
      if: ${{ inputs.cli-version != '' && inputs.custom-github-ref == '' }}
      shell: bash
      run: uv tool install snowflake-cli==${{ inputs.cli-version }}

    - name: Install snowflake-cli (custom ref)
      if: ${{ inputs.cli-version == '' && inputs.custom-github-ref != '' }}
      shell: bash
      run: uv tool install "git+https://github.com/snowflakedb/snowflake-cli.git@${{ inputs.custom-github-ref }}"

    - name: Install snowflake-cli (latest release)
      if: ${{ inputs.cli-version == '' && inputs.custom-github-ref == '' }}
      shell: bash
      run: uv tool install snowflake-cli

    - name: Set up config.toml
      shell: bash
      run: bash $GITHUB_ACTION_PATH/scripts/setup-config-file.sh
      env:
        CONFIG_FILE_PATH: ${{ inputs.default-config-file-path }}

    - name: Set up workload identity authentication
      if: ${{ inputs.use-oidc == 'true' }}
      shell: bash
      run: |
        echo "SF_ENABLE_EXPERIMENTAL_AUTHENTICATION=true" >> "$GITHUB_ENV"
        echo "SNOWFLAKE_AUTHENTICATOR=WORKLOAD_IDENTITY" >> "$GITHUB_ENV"
        echo "SNOWFLAKE_AUDIENCE=snowflakecomputing.com" >> "$GITHUB_ENV"
        TOKEN_NAME_UPPER=$(echo ${{ inputs.oidc-token-name }} | tr '[:lower:]' '[:upper:]')
        echo "${TOKEN_NAME_UPPER}=$(snow auth oidc read-token --type=github)" >> "$GITHUB_ENV"
