# action.yml
name: 'Install Snowflake CLI'
description: 'Download and install snowflake-cli through pipx'
branding:
  icon: 'terminal'
  color: 'blue'
  
inputs:
  cli-version:
    description: 'Snowflake CLI version (by default, installs the latest version)'
    required: false

  default-config-file-path:
    description: 'Path to the default config file'
    required: false
    default: './config.toml'

  custom-github-ref:
    description: 'GitHub branch, tag, or commit to install from (if set, installs from GitHub; otherwise, installs from PyPI)'
    required: false

  use-workload-identity:
    description: 'Enable workload identity authentication'
    required: false
    default: 'false'

  workload-identity-token-name:
    description: 'Name of the token environment variable for workload identity'
    required: false
    default: 'SNOWFLAKE_TOKEN'

  oidc-audience:
    description: 'OIDC audience for workload identity authentication'
    required: false
    default: 'snowflakecomputing.com'

runs:
  using: 'composite'
  steps:
    - name: add extra telemetry data
      shell: bash
      run: echo "SF_GITHUB_ACTION=true" >> "$GITHUB_ENV"

    - name: >
        Download snowflake-cli
        ${{ inputs.custom-github-ref && format('from git ref {0}', inputs.custom-github-ref) || (inputs.cli-version && format('version {0}', inputs.cli-version) || 'latest version') }}
      shell: bash
      run: bash $GITHUB_ACTION_PATH/scripts/install-snowcli.sh
      env:
        CLI_VERSION: ${{ inputs.cli-version }} 
        CUSTOM_GITHUB_REF: ${{ inputs.custom-github-ref }}
    - name: Set up config.toml
      shell: bash
      run: bash $GITHUB_ACTION_PATH/scripts/setup-config-file.sh
      env:
        CONFIG_FILE_PATH: ${{ inputs.default-config-file-path }}
    - name: Set up workload identity authentication
      if: ${{ inputs.use-workload-identity == 'true' }}
      shell: bash
      env:
        SNOWFLAKE_AUDIENCE: ${{ inputs.oidc-audience }}
      run: |
        echo "SF_ENABLE_EXPERIMENTAL_AUTHENTICATION=true" >> "$GITHUB_ENV"
        echo "SNOWFLAKE_AUDIENCE=${{ inputs.oidc-audience }}" >> "$GITHUB_ENV"
        echo "SNOWFLAKE_AUTHENTICATOR=WORKLOAD_IDENTITY" >> "$GITHUB_ENV"
        TOKEN_NAME="${{ inputs.workload-identity-token-name }}"
        TOKEN_NAME_UPPER=$(echo "$TOKEN_NAME" | tr '[:lower:]' '[:upper:]')
        snow auth workload-identity read --debug
        TOKEN_VALUE=$(snow auth workload-identity read --type=github)
        echo "${TOKEN_NAME_UPPER}=${TOKEN_VALUE}" >> "$GITHUB_ENV"

