# action.yml
name: 'Install Snowflake CLI'
description: 'Download and install snowflake-cli through pipx'
branding:
  icon: 'terminal'
  color: 'blue'
  
inputs:
  cli-version:
    description: 'Snowflake CLI version'
    required: false

  install-from-github:
    description: 'Install Snowflake CLI from GitHub repository (true/false)'
    required: false
    default: 'false'

  custom-github-ref:
    description: 'GitHub branch, tag, or commit to install from (if set, installs from GitHub; otherwise, installs from PyPI)'
    required: false

  default-config-file-path:
    description: 'Path to the default config file'
    required: false
    default: './config.toml'

runs:
  using: 'composite'
  steps:
    - name: Download snowflake-cli ${{ inputs.cli_version }}
      shell: bash
      run: bash $GITHUB_ACTION_PATH/scripts/install-snowcli.sh
      env:
        CLI_VERSION: ${{ inputs.cli-version }} 
        CUSTOM_GITHUB_REF: ${{ inputs.custom-github-ref }}

    - name: Set up config.toml
      shell: bash
      run: bash $GITHUB_ACTION_PATH/scripts/setup-config-file.sh
      env:
        CONFIG_FILE_PATH: ${{ inputs.default-config-file-path }} 
