name: test-install-snowcli-from-github-prerelease
on: [push]

jobs:
  test-install-from-github-prerelease:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
    name: Install Snowflake CLI from GitHub pre-release v3.9.0-rc1 in ${{ matrix.os }} with Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Snowflake CLI from GitHub pre-release
        uses: ./
        id: setup_snowcli_github_prerelease
        with:
          install-from-github: true
          custom-github-ref: "v3.9.0-rc1"
      - name: Test snow installation from GitHub pre-release
        shell: bash
        run: |
          snow --version
          snow -h 