name: test-empty-pipx-bin-dir
on: [push]

jobs:
  test-empty-pipx-bin-dir:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    env:
      PIPX_BIN_DIR: ""

    name: Install Snowflake CLI in ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Snowflake CLI
        uses: ./
        id: setup_snowcli

      - name: List connections
        shell: bash
        run: |
          snow -h
